# Generated by Django 4.2.6 on 2023-11-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0002_alter_mailing_mailing_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('created', 'создана'), ('started', 'запущена'), ('completed', 'завершена')], max_length=50, verbose_name='Статус'),
        ),
    ]
