# Generated by Django 4.2.6 on 2023-11-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0003_remove_mailinglog_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing_app.mailing', verbose_name='Рассылка'),
        ),
    ]
