# Generated by Django 4.2.6 on 2023-11-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0004_alter_message_mailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='Время изменения'),
        ),
    ]
