# Generated by Django 4.2.6 on 2023-11-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0007_alter_mailing_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('disable_mailing', 'Can switch-off mailings')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
